<?php
// This file generated by Propel 1.6.7 convert-conf target
// from XML runtime conf file /home/webde/public_html/application/build/data/runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'webmaster' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'dsn' => 'mysql:host=localhost;dbname=webde_webmaster',
        'user' => 'webde_webmaster',
        'password' => 'i]zas81od~Pu',
      ),
    ),
    'default' => 'webmaster',
  ),
  'generator_version' => '1.6.7',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap-webmaster-conf.php');
return $conf;